name: Build

on:
  push:
    branches: [ main ]
    paths: [ .github/workflows/build.yml, config/**, docker/**, scripts/**]
  pull_request:
    branches: [ main ]
    paths: [ .github/workflows/build.yml, config/**, docker/**, scripts/**]
  workflow_dispatch:

permissions: { }

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, arm64 ]
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/${{ matrix.target }}.Dockerfile
          pull: true
          push: false
          tags: ink-toolchain:dev
          platforms: linux/${{ matrix.platform }}
          builder: ${{ steps.buildx.outputs.name }}
      - name: Extract
        run: TARGETARCH='${{ matrix.platform }}' ./scripts/extract.sh
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.platform }}+${{ matrix.target }}"
          path: |
            export/${{ matrix.target }}.tar.gz
