name: Release

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, arm64 ]
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/${{ matrix.target }}.Dockerfile
          no-cache: true
          pull: true
          push: false
          tags: ink-toolchain:dev
          platforms: linux/${{ matrix.platform }}
          builder: ${{ steps.buildx.outputs.name }}
      - name: Extract
        run: TARGETARCH='${{ matrix.platform }}' ./scripts/extract.sh
      - name: Rename
        shell: bash
        working-directory: ./export
        run: for f in *.tar.gz; do mv "$f" "${{ matrix.platform }}+$f"; done
      - name: Hash
        shell: bash
        working-directory: ./export
        run: for f in *.tar.gz; do sha256sum "$f" > "$f".sha256; done
      - name: Create and push artifacts to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "./export/*.tar.gz,./export/*.sha256"
